### ISSUE TITLE
ダメージ判定プログラムの作成

### ISSUE THREAD

**Issue by Subaru-K** [Subaru-K/GoToTsukuba#2]
目標

- 当たったらダメージを受けるコンポーネントを作成し、オブジェクトに張り付ける

条件

- プレイヤーではなく、敵や環境にコンポーネント(プログラム)をつけるようにする
- HPの実装は後回しなので当たったらダメージを右上に表示とかでいい
- ダメージはプログラム内で決めるのではなくUnity内でコンポーネントの設定を入力できるようにする

手順(適当)

1. シーンを適当に作って平らなマップを作る(できればタイルマップを使って慣れておいてほしい)
2. 適当に画像(四角いやつでいい)を選んで当たり判定を作る
3. ダメージを計算？して表示するプログラム(画面右上とか任せる)を書く。
4. 当たり判定を付けたオブジェクトに張り付ける。

パッと思うこと。

- ダメージをプログラムで書き換えると一つ一つの敵やエリアに別のプログラムが必要になるから、入力できるようにしといてほしい。変数を(public int)で書いとけばそうなるはず。
- 誰に当たったか==Playerとかにすれば簡単にできる気がするのでよろしく。
- どういうゲームにするかまだ具体性がないからダメージとか使わなくなるかもだけどそこは話し合おう。

**Comment by KindMaple** [comment]
プレイヤーに当たったらログにダメージ量を表示することはできた。
画面上のテキストUIに表示する方法がいまいち理解できてなくて詰まってる。
